apiVersion: v2
appVersion: 1.0.0
description: A guestbook Helm chart for Kubernetes.
name: guestbook
version: 0.1.0
dependencies:
- name: redis
  version: 12.4.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
  tags:
    - redis-database