apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "guestbook.fullname" . }}
  labels:
    app: {{ template "guestbook.name" . }}
    chart: {{ template "guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "guestbook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "guestbook.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
          - name: GET_HOSTS_FROM
            value: env
          - name: REDIS_MASTER_SERVICE_HOST
          {{- if .Values.redis.enabled }}
            value: {{ template "guestbook.name" . }}-redis-master
          {{- else }}
            value: {{ .Values.externalDatabase.host | quote }}
          {{- end }}
          - name: REDIS_SLAVE_SERVICE_HOST
          {{- if .Values.redis.enabled }}
            {{- if .Values.redis.cluster.enabled }}
            value: {{ template "guestbook.name" . }}-redis-slave
            {{- else }}
            value: {{ template "guestbook.name" . }}-redis-master
            {{- end }}
          {{- else }}
            value: {{ .Values.externalDatabase.host | quote }}
          {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
